### ISSUE TITLE
"localStorage is not defined" on ReactNative

### ISSUE THREAD

**Issue by VonderVuflya** [storeon/localstorage#27]
### How to save store changes in "localStorage" on ReactNative?

Hi, I use storeon in ReactNative and want to save my store to localStorage, but RN does not have localStorage, RN used AsyncStorage for this. I try to change storage in persistState config but it doesn't work, after restart app, the store goes initial.

![image](https://user-images.githubusercontent.com/17604053/72770061-d2f90d00-3c0d-11ea-931d-0414fe05a2e5.png)

**Comment by polemius** [comment]
@VonderVuflya what version of react native and localstorage are you using?

With this dependencies:

```
"@react-native-community/async-storage": "^1.7.1",
"@storeon/localstorage": "^0.9.0",
"react-native": "0.61.5",
```
I did not have any errors but still it doesn't work because in `AsyncStorage` functions should be fired with `await`. And another problem in storeon page that I described in https://github.com/storeon/storeon/issues/92

I will wait for answering for this issue and will try figure out how use `localstorage` with react native and `AsyncStorage`.

**Comment by polemius** [comment]
@VonderVuflya I have released new version of this library. Please check your code with version `0.10.0`

**Comment by VonderVuflya** [comment]
Thanks!
Now all work great
But there's one interesting thing
In launched moment app, I checked the condition and dispatch store, but now I've need first get the async store and then dispatch otherwise dispatch store was faster than store rehydrate

![image](https://user-images.githubusercontent.com/17604053/73257294-89dc2680-41d4-11ea-89c9-910a9a89072f.png)

**Comment by VonderVuflya** [comment]
Sorry, my bad, all work correctly and I don't needed get async store

![image](https://user-images.githubusercontent.com/17604053/73441074-76ab9100-4363-11ea-97b7-fe469dbbd8bf.png)
